---
all:
  children:
    ios:
      children:
        routers:
          children:
            batch_b:
              hosts:
                ro1:
                  ansible_host: 192.168.1.251
                  ansible_port: 22
                  telnet_host: 10.225.2.200
                  telnet_port: 22521
                ro2:
                  ansible_host: 192.168.1.252
                  ansible_port: 22
                  telnet_host: 10.225.2.200
                  telnet_port: 22522
        switches:
          children:
            batch_a:
              hosts:
                sw1:
                  ansible_host: 192.168.1.241
                  ansible_port: 22
                  telnet_host: 10.225.2.200
                  telnet_port: 22521
                sw2:
                  ansible_host: 192.168.1.242
                  ansible_port: 22
                  telnet_host: 10.225.2.200
                  telnet_port: 22522
                sw3:
                  ansible_host: 192.168.1.243
                  ansible_port: 22
                  telnet_host: 10.225.2.200
                  telnet_port: 22523
                sw4:
                  ansible_host: 192.168.1.244
                  ansible_port: 22
                  telnet_host: 10.225.2.200
                  telnet_port: 22524
            batch_b:
              hosts:
                sw5:
                  ansible_host: 192.168.1.245
                  ansible_port: 22
                  telnet_host: 10.225.3.200
                  telnet_port: 22534

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_ssh_common_args: '-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-rsa -o Ciphers=aes128-cbc'
    ansible_user: example
    ansible_password: example
    ansible_become_method: enable

...
