---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        files: .*\.(yaml|yml)$
        args: [--unsafe]
      - id: check-json
      - id: check-xml
      - id: check-toml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs

...
