---
all:
  vars:
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
  children:
    clients:
      hosts:
        capsule:
          ansible_host: 192.168.21.100
          ansible_user: root
          ansible_password: rootroot
...
